"""empty message

Revision ID: 13fab1906eea
Revises: 7bb0b6d72009
Create Date: 2026-01-03 20:18:40.089973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fab1906eea'
down_revision = '7bb0b6d72009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_link', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_column('img_link')

    # ### end Alembic commands ###
