"""empty message

Revision ID: 1e9b07fc26b5
Revises: 13fab1906eea
Create Date: 2026-01-03 20:25:29.623685

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e9b07fc26b5'
down_revision = '13fab1906eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('img_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_link', sa.String(length=300), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
