"""empty message

Revision ID: 7bb0b6d72009
Revises: e4accac700b1
Create Date: 2026-01-03 19:45:47.312781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb0b6d72009'
down_revision = 'e4accac700b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coingecko_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['coingecko_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('coingecko_id')

    # ### end Alembic commands ###
