"""empty message

Revision ID: a36d3719e4ed
Revises: e904d1726966
Create Date: 2026-01-14 10:55:06.175548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36d3719e4ed'
down_revision = 'e904d1726966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('venda', 'compra', name='transaction_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
