"""empty message

Revision ID: c2f793bd075a
Revises: 1e9b07fc26b5
Create Date: 2026-01-05 09:50:47.100837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f793bd075a'
down_revision = '1e9b07fc26b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('symbol'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('symbol'), ['symbol'], unique=True)

    # ### end Alembic commands ###
