"""empty message

Revision ID: e904d1726966
Revises: c2f793bd075a
Create Date: 2026-01-05 17:44:51.044212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e904d1726966'
down_revision = 'c2f793bd075a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True))
        batch_op.add_column(sa.Column('current_marketcap', sa.Numeric(precision=25, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_change_percentage_24h', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('price_change_percentage_24h')
        batch_op.drop_column('current_marketcap')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
